import { useEffect, useState } from 'react';
import { Dices, ShieldCheck, Square } from 'lucide-react';
import { failureCeiling, landabilityLog2 } from '../fuzz';
import { ecdsaPoints, labDefaults, parameters } from '../sources';
import { FailureSummary } from './dialog-view';
import { LogPlot } from './plot';
import { Cite, Derivation, integer, percent, SectionTitle, Status } from './shared';
import { useLabWorker } from './use-lab-worker';

export function FuzzView() {
  const [testCount, setTestCount] = useState(String(parameters.tests));
  const [drawBound, setDrawBound] = useState('1');
  const [confidenceText, setConfidenceText] = useState('99');
  const [unknownDraws, setUnknownDraws] = useState(true);
  const [demoCount, setDemoCount] = useState<number>(labDefaults.demoTests);
  const [iterationFactor, setIterationFactor] = useState<number>(labDefaults.demoIterationFactor);
  const [smallField, setSmallField] = useState(false);
  const [trials, setTrials] = useState<{ round: number; draws: number; expected: number }[]>([]);
  const worker = useLabWorker();
  const tests = Number(testCount);
  const draws = Number(drawBound);
  const confidence = Number(confidenceText) / 100;
  const valid = Number.isSafeInteger(tests) && tests > 0 && tests <= 1000000 && confidence > 0 && confidence < 1 && Number.isFinite(confidence) && (unknownDraws || (Number.isFinite(draws) && draws >= 1));
  const ceiling = valid && !unknownDraws ? failureCeiling(tests, draws, confidence) : null;
  const points = valid ? Array.from({ length: labDefaults.nonceBits + 1 }, (_, exponent) => [exponent, failureCeiling(tests, 2 ** exponent, confidence) * 100] as const) : [];
  const sourceLog = landabilityLog2(parameters.failureThreshold, parameters.tests);
  const caseLog = landabilityLog2(1 - ecdsaPoints.windowed.success, parameters.tests);
  const prime = smallField ? parameters.smallField : parameters.fieldPrime;
  const currentGrind = worker.grind;
  useEffect(() => {
    if (!currentGrind?.draw.landed) return;
    const expected = 2 ** -landabilityLog2(currentGrind.calibration.rate, currentGrind.draw.tests);
    setTrials(previous => [...previous, { round: (previous.at(-1)?.round ?? 0) + 1, draws: currentGrind.draws, expected }].slice(-12));
  }, [currentGrind]);

  function retire() {
    worker.retire();
    setTrials([]);
  }

  return <>
    <SectionTitle number="03" title="What 9,024 tests prove">A flawed program can miss every failing input in a small test set. Repeating the draw gives it more chances to get lucky, even when its behavior never improves.</SectionTitle>
    <div className="evidence-statement"><div><span className="eyebrow">A program wrong on 1% of inputs</span><strong>2<sup>{sourceLog.toFixed(2)}</sup></strong><span>chance of a clean {integer(parameters.tests)}-test draw</span></div><div><p className="formula">P(clean draw) = (1 &minus; &epsilon;)<sup>N</sup></p><p className="formula">P(any clean draw) &le; min(1, G &times; (1 &minus; &epsilon;)<sup>N</sup>)</p><Cite source="google" locator="Appendix A.5" /><Derivation name="landability" /></div></div>
    <div className="subsection"><h3>The ceiling depends on the draw budget</h3><p className="small muted">After a clean run, exclude larger error rates at the chosen confidence. This is a statistical test under the stated model, not a probability that the program is correct.</p><div className="control-grid"><label className="field">Tests N<input aria-label="Ceiling test count" type="number" min={1} max={1000000} step={1} value={testCount} onChange={event => setTestCount(event.target.value)} /></label><label className="field">Draw bound G<input aria-label="Draw bound G" type="number" min={1} step={1} disabled={unknownDraws} value={drawBound} onChange={event => setDrawBound(event.target.value)} /></label><label className="field">Confidence (%)<input aria-label="Confidence percent" type="number" min={1} max={99.999999} step={0.1} value={confidenceText} onChange={event => setConfidenceText(event.target.value)} /></label></div><label className="check-label"><input type="checkbox" checked={unknownDraws} onChange={event => setUnknownDraws(event.target.checked)} />The number of draws is unknown</label>
      {!valid ? <Status tone="fail">Enter a positive integer N up to 1,000,000, G at least one, and confidence strictly between 0% and 100%.</Status> : <>
        {ceiling === null ? <Status tone="warn" testId="unknown-ceiling">Unknown G: no single certified ceiling. The curve shows what different bounded draw budgets would support.</Status> : <Status testId="ceiling-result" verdict="conditional-ceiling"><strong>Conditional ceiling &le; <span data-testid="ceiling-value">{percent(ceiling, 4)}</span></strong> after a clean run, at {confidenceText}% confidence and G &le; {integer(draws)}.</Status>}
        <LogPlot testId="ceiling-plot" series={[{ name: 'Error-rate exclusion ceiling', color: '#35d6bb', points }]} xLabel="log2(draw bound G)" yLabel="epsilon* (%)" description={`At N = ${integer(tests)} and ${confidenceText}% confidence, more permitted draws weaken the supported failure-rate ceiling. No selected point is shown when G is unknown.`} />
        <div className="ceiling-references">{[1, 1e8, 2 ** 48].map(bound => <div key={bound}><span>G = {bound === 2 ** 48 ? '2^48' : integer(bound)}</span><strong>{percent(failureCeiling(tests, bound, confidence), 3)}</strong></div>)}</div>
        <Derivation name="ceiling" />
        <p className="caveat">The model assumes independent random-oracle draws, correct checker code, a declared input distribution, and an upper bound on all attempted draws, including discarded ones. At Google's 1% threshold, even G = 2<sup>27</sup> leaves a bound of 2<sup>{(sourceLog + 27).toFixed(2)}</sup>.</p>
        <details className="wide-disclosure"><summary>Clean-draw probability on a logarithmic scale</summary><LogPlot testId="landability-plot" series={[{ name: '1% input error rate', color: '#f1c27b', points: Array.from({ length: 61 }, (_, index) => { const count = Math.max(1, Math.round(parameters.tests * index / 60)); return [count, 2 ** landabilityLog2(parameters.failureThreshold, count)] as const; }) }]} xLabel="independent tests N" yLabel="P(clean draw)" description="Each added independent test makes a clean draw less likely for a program with a fixed one-percent error rate. The vertical axis is logarithmic." /></details>
      </>}
    </div>

    <div className="subsection"><h3><Dices size={19} aria-hidden="true" />Find a clean draw</h3><span className="tag">DEMO SCALE / no circuit submission</span><p>This is the Act 2 multiplier with a smaller iteration margin. Each nonce changes the committed bytes and re-draws the tests; it does not repair the multiplier.</p>
      <div className="workbench"><div className="control-grid"><label className="field">Tests per draw N_demo<select aria-label="Demo tests per draw" value={demoCount} onChange={event => { const value = Number(event.target.value); if (value !== demoCount) { retire(); setDemoCount(value); } }}><option value={4}>4</option><option value={8}>8</option><option value={16}>16</option><option value={32}>32</option></select></label><label className="field">Iteration margin c_iter <strong>{iterationFactor.toFixed(1)}</strong><input type="range" aria-label="Grind iteration margin" min={-1} max={2.4} step={0.1} value={iterationFactor} onChange={event => { const value = Number(event.target.value); if (value !== iterationFactor) { retire(); setIterationFactor(value); } }} /></label><label className="field">Field<select aria-label="Grind field" value={smallField ? 'small' : 'secp'} onChange={event => { const value = event.target.value === 'small'; if (value !== smallField) { retire(); setSmallField(value); } }}><option value="secp">secp256k1 / 256 bits</option><option value="small">Demo / 2^61 - 1</option></select></label></div>
        <div className="button-row"><button className="primary" disabled={worker.busy} onClick={() => worker.start({ kind: 'grind', config: { prime, iterationFactor, paddingFactor: parameters.paddingFactor }, count: demoCount, maxDraws: labDefaults.maxDraws })}><Dices size={17} aria-hidden="true" />Grind nonces</button>{worker.busy && <button onClick={() => worker.retire('Grinding cancelled; no clean-draw claim retained.')}><Square size={14} aria-hidden="true" />Cancel grinding</button>}<span className="small muted">Up to {labDefaults.maxDraws} draws; {labDefaults.calibrationCount} independent calibration cases</span></div>
        {worker.busy && <Status>{worker.progress.phase}: {worker.progress.completed} / {worker.progress.total}<progress value={worker.progress.completed} max={worker.progress.total} aria-label="Grinding progress" /></Status>}{worker.notice && <Status testId="grind-retired">{worker.notice}</Status>}{worker.error && <Status tone="fail">{worker.error}</Status>}
        {currentGrind && <>
          <Status tone={currentGrind.draw.landed ? 'warn' : 'fail'} verdict={currentGrind.draw.landed ? 'lands' : 'no-clean-draw'} testId="grind-verdict"><strong>{currentGrind.draw.landed ? 'CLEAN DRAW: all selected checks pass, not all-input correctness.' : `No clean draw found within ${currentGrind.draws} attempts.`}</strong> {currentGrind.draws} draw{currentGrind.draws === 1 ? '' : 's'} tried; final nonce {currentGrind.draw.nonce}.</Status>
          {currentGrind.draw.landed && <p className="caveat" data-testid="negative-claim">A clean draw does not establish all-input correctness. This same multiplier budget rejects x = p - 1; the selected checks simply did not certify every input.</p>}
          <div className="draw-strip" role="img" aria-label={`${currentGrind.history.length} draws, ${currentGrind.draw.landed ? 'last draw clean' : 'none clean'}`}>{currentGrind.history.map(attempt => <span key={attempt.draw} title={`Draw ${attempt.draw}: ${attempt.checked} checks, ${attempt.landed ? 'clean' : 'failure'}`} className={attempt.landed ? 'landed' : ''} />)}</div>
          <dl className="hex-list"><dt>SHA-256 commitment</dt><dd data-testid="commitment">{currentGrind.draw.commitment}</dd><dt>Maximum observed draw</dt><dd data-testid="draw-duration">{currentGrind.maxDrawMs.toFixed(2)} ms</dd></dl>
          {currentGrind.maxDrawMs >= labDefaults.drawBudgetMs && <Status tone="warn">This machine exceeded the {labDefaults.drawBudgetMs} ms draw target. The smaller field is available for a faster demonstration.</Status>}
          <FailureSummary estimate={currentGrind.calibration} />
          <p className="small muted">Calibration is measured independently of nonce-selected inputs. The expected-draw curve uses the plug-in estimate (1 - epsilon-hat)^(-N_demo), not a guarantee for any individual run.</p>
          <details className="wide-disclosure"><summary>Inspect the final draw</summary><div className="table-scroll" role="region" aria-label="Final fuzz draw" tabIndex={0}><table className="draw-table"><thead><tr><th scope="col">Input x / hex</th><th scope="col">y / hex</th><th scope="col">BigInt expected</th><th scope="col">Dialog output</th><th scope="col">Sample check</th></tr></thead><tbody>{currentGrind.draw.samples.map((sample, index) => <tr key={index}><td><code>{sample.input}</code></td><td><code>{sample.multiplicand}</code></td><td><code>{sample.expected}</code></td><td><code>{sample.actual}</code></td><td data-testid="sample-check">{sample.passed ? 'pass' : sample.reason}</td></tr>)}</tbody></table></div></details>
        </>}
        {trials.length > 0 && <LogPlot testId="grind-plot" series={[{ name: 'Observed draws to land', color: '#f1c27b', points: trials.map(trial => [trial.round, trial.draws]) }, { name: 'Calibration plug-in expectation', color: '#9acfee', points: trials.map(trial => [trial.round, trial.expected]) }]} xLabel="completed experiment" yLabel="draws" description="Actual draws to a clean test set, compared with the expectation estimated from independent calibration. Experiments with unchanged parameters begin from the same nonce and are deterministic; the calibration is freshly random." />}
        <details className="wide-disclosure"><summary>Exactly what is committed and sampled</summary><p>The commitment is SHA-256(implementation bytes + canonical parameters + codec, then a fixed-width six-byte big-endian nonce). SHAKE256 is seeded with those exact same bytes, not with the SHA-256 digest. The serialized payload is JSON in a fixed property order.</p><p>Each demo case draws a nonzero x and y using masked, big-endian rejection sampling. Zero and candidates at least p are discarded, never reduced. Google instead samples curve points as G*k and also uses the same XOF for simulated measurement outcomes. This lab does not simulate those outcomes.</p><Cite source="google" locator="Appendix A.5-A.6" /></details>
      </div>
    </div>
    <div className="subsection two-column"><div><h3>ECDSA.Fail's documented mechanism</h3><p>A {labDefaults.nonceBits}-bit nonce chooses which target receives each X-X identity pair in a 96-operation tail. The function stays the same, but the hash and test set change.</p><p>At the paper's measured p-hat = {ecdsaPoints.windowed.success}, a clean {integer(parameters.tests)}-case draw has probability <strong>{(2 ** caseLog).toExponential(2)}</strong>: about <strong>{integer(2 ** -caseLog)}</strong> draws in the model.</p><p>A union bound over {2 * parameters.fieldBits / parameters.window - 4} calls gives at most <strong>{percent((1 - ecdsaPoints.windowed.success) * (2 * parameters.fieldBits / parameters.window - 4), 2)}</strong> failure, using that per-call estimate. This is not a validated full-Shor failure rate.</p><Cite source="ecdsa" locator="3.3, Table 3 and 6" /><Derivation name="compounding" /><Derivation name="landability" /></div><div><h3>What zero failures can support</h3><p>Schrottenloher reports failure at most 2<sup>&minus;13.3</sup>, approximately one in ten thousand, from zero failures in ten thousand runs.</p><p>The 95% rule-of-three upper bound from those observations is <strong>{percent(3 / 10000, 3)}</strong>, approximately 2<sup>{Math.log2(3 / 10000).toFixed(1)}</sup>.</p><p className="small muted">The source's statement and this confidence bound are different claims. Neither is an all-inputs proof.</p><Cite source="dialog" locator="Table 1 caption" /><Derivation name="schrottenloher" /></div></div>
    <div className="subsection"><h3><ShieldCheck size={18} aria-hidden="true" />Change who chooses the tests</h3><div className="two-column"><div><h4>Verifier-held randomness</h4><p>A fresh verifier seed after the commitment removes prover choice over the tested draw, so G = 1 for a single fixed commitment.</p>{valid && <p className="formula">At N = {integer(tests)}: epsilon* = {percent(failureCeiling(tests, 1, confidence), 4)}</p>}<p className="small muted">The brief mentions an ecdlp-contest hard mode with 102,400 shots. Its README was not located; that benchmark-specific count is not used as verified evidence here.</p></div><div><h4>A post-commitment public beacon</h4><p>Commit first, then use public randomness that cannot be selected in advance. With one fixed commitment and no selective restarts, the model again uses G = 1.</p>{valid && <p className="formula">At N = {integer(tests)}: epsilon* = {percent(failureCeiling(tests, 1, confidence), 4)}</p>}<Cite source="critic" locator="Post-submission public-beacon proposal" /></div></div><Derivation name="ceiling" /></div>
    <div className="subsection contested"><h3>Two accounts of nonce hunting</h3><div className="two-column"><div><span className="eyebrow">Organizers</span><p>Exactness is not required. Submitters search for a clean validation island using the documented nonce tail. Section 6 also notes that support selection can lower sampled gate counts without a semantic circuit improvement.</p><Cite source="ecdsa" locator="3.3 and 6, read in full for this lab" /></div><div><span className="eyebrow">Critic / third-party, self-reported</span><p>abipalli argues that the then-leading {integer(ecdsaPoints.criticBest.toffoli)} T &times; {integer(ecdsaPoints.criticBest.qubits)} Q entry violated the README's no-tuning rule. They report an all-inputs-exact alternative at {integer(ecdsaPoints.criticExact.toffoli)} T &times; {integer(ecdsaPoints.criticExact.qubits)} Q, reproduced by the benchmark evaluator according to their account.</p><Cite source="critic" locator="17 Jun writeup and author's repository" /></div></div><p className="small muted">The lab presents the accounts and the statistical model without adjudicating the dispute. Approximation by itself does not imply failure under Google's stated approximate-correctness standard.</p><details className="wide-disclosure"><summary>The two different initial baselines</summary><p>README: {integer(ecdsaPoints.readmeBaseline.toffoli)} T &times; {integer(ecdsaPoints.readmeBaseline.qubits)} Q = {integer(ecdsaPoints.readmeBaseline.toffoli * ecdsaPoints.readmeBaseline.qubits)}.</p><p>Paper: {integer(ecdsaPoints.paperBaseline.toffoli)} T &times; {integer(ecdsaPoints.paperBaseline.qubits)} Q = {integer(ecdsaPoints.paperBaseline.toffoli * ecdsaPoints.paperBaseline.qubits)}. Its reduction to the cutoff product is {((1 - ecdsaPoints.cutoff.toffoli * ecdsaPoints.cutoff.qubits / (ecdsaPoints.paperBaseline.toffoli * ecdsaPoints.paperBaseline.qubits)) * 100).toFixed(1)}%.</p><Cite source="challenge" locator="Reference numbers" /><Cite source="ecdsa" locator="5.1.1" /><Derivation name="ecdsa" /></details></div>
  </>;
}