import { useState } from 'react';
import { ArrowRight, Check, Cpu, Fingerprint, LockKeyhole, Shuffle } from 'lucide-react';
import { toyRoundTrip } from '../kickmix-toy';
import { parameters, proofFacts, relatedLabs, timeline } from '../sources';
import { Cite, integer, SectionTitle, Status } from './shared';

const pipeline = [
  { name: 'Commit the bytes', icon: Fingerprint, content: 'SHA-256 binds the exact circuit-file bytes. A public commitment identifies the private input that the program was run against.' },
  { name: 'Generate and test', icon: Shuffle, content: 'SHAKE256 uses those bytes to generate the test inputs. The kickmix simulator also takes simulated measurement outcomes from the same XOF stream.' },
  { name: 'Assert resources', icon: Check, content: 'The guest checks functional results and resource limits. The reported non-Clifford count is the average executed CCX + CCZ count across the tested cases.' },
  { name: 'Prove execution', icon: Cpu, content: 'The guest runs as SP1 RISC-V. Execution is divided into STARK shards, then combined through recursion. This attests execution of the guest program, including its mistakes if the program is wrong.' },
  { name: 'Wrap in Groth16', icon: LockKeyhole, content: "SP1's individual STARK proofs are not zero-knowledge. A Groth16 wrapper supplies zero knowledge and succinctness. This lab generates no proof." },
];

export function ProofView() {
  const [stage, setStage] = useState(0);
  const [aliased, setAliased] = useState(true);
  const [aliasCheck, setAliasCheck] = useState(true);
  const [result, setResult] = useState<ReturnType<typeof toyRoundTrip> | null>(null);
  const [reversed, setReversed] = useState(false);
  const [retired, setRetired] = useState(false);
  function retire() {
    if (result) setRetired(true);
    setResult(null);
    setReversed(false);
  }
  return <>
    <SectionTitle number="04" title="What the proof proves">The proof can attest that a checker ran faithfully without revealing its private circuit. It cannot repair the checker, choose its assumptions, or turn a sampled test into an all-inputs theorem.</SectionTitle>
    <p className="small muted">For the underlying zero-knowledge idea, see <a href={relatedLabs.zk}>ZK Proof Lab</a>. Here the question is what this particular statement binds.</p>
    <ol className="pipeline-strip" role="list">{pipeline.map((item, index) => <li key={item.name} role="listitem"><button aria-pressed={stage === index} onClick={() => setStage(index)}><item.icon size={22} aria-hidden="true" /><span className="eyebrow">0{index + 1}</span><strong>{item.name}</strong></button></li>)}</ol>
    <div className="pipeline-detail" role="status"><h3>{pipeline[stage].name}</h3><p>{pipeline[stage].content}</p>{stage === 1 && <p className="formula">{integer(parameters.tests)} circuit-dependent test inputs</p>}{stage === 3 && <p className="formula">Approximately 2<sup>22</sup> = {integer(proofFacts.shardInstructions)} instructions per shard</p>}<Cite source="google" locator="Appendix A.6-A.7" /></div>
    <div className="subsection two-column"><div><h3>A commitment binds bytes</h3><p>The v1 to v2 hashes changed because the hashed representation changed: serialized parsed object in v1, circuit-file contents in v2. Google says the underlying circuits did not change.</p><p className="caveat">Serialization is part of the statement. Equal behavior does not imply equal committed bytes.</p><Cite source="google" locator="Appendix A.7" /></div><div><h3>The attestation has its own assumptions</h3><p>Groth16 relies on pairing-friendly elliptic curves. Google notes that a sufficiently capable quantum computer could undermine the soundness of this wrapper, the same class of risk studied in the paper.</p><Cite source="google" locator="Appendix A.6, final paragraph" /></div></div>
    <div className="subsection"><h3>The checker is part of the claim</h3><p>Trail of Bits produced a forged resource claim that verified under the unpatched guest program. This was a checker failure, not a cheaper point-addition circuit.</p><div className="forged-metrics"><div><span className="eyebrow">Claimed Toffoli</span><strong>{proofFacts.forgedToffoli}</strong></div><div><span className="eyebrow">Claimed qubits</span><strong>{integer(proofFacts.forgedQubits)}</strong></div><div><span className="eyebrow">Claimed operations</span><strong>~{proofFacts.forgedOperations / 1e6}M</strong></div></div><p>The real circuit behind the claim used <strong>{integer(proofFacts.actualToffoli)}</strong> Toffoli operations before the bypass.</p><div className="two-column"><div><h4>1 / Unchecked deserialization</h4><p>The guest used unchecked rkyv deserialization. An out-of-range opcode could jump past the Toffoli counter's jump table. This bug is described here, not reproduced.</p></div><div><h4>2 / Operand aliasing</h4><p>The checker did not require distinct CCX operands. With the target and both controls on the same bit, the classical assignment becomes q = q XOR (q AND q) = 0, which erases information.</p></div></div><Cite source="tob" locator="17 Apr 2026 postmortem" /></div>
    <div className="workbench"><div className="section-toolbar"><h3>One check, two very different meanings</h3><span className="tag">toy written for this lab, not Google's code</span></div><p className="small muted">Classical basis-bit stepper, at most eight bits. It does not simulate a quantum state or run a real guest program.</p><div className="section-toolbar"><div className="segmented" role="group" aria-label="Toy CCX operands"><button aria-pressed={aliased} onClick={() => { if (!aliased) { retire(); setAliased(true); } }}>CCX(q, q, q)</button><button aria-pressed={!aliased} onClick={() => { if (aliased) { retire(); setAliased(false); } }}>CCX(q0, q1, q2)</button></div><label className="check-label"><input type="checkbox" aria-label="Check operand aliasing" checked={aliasCheck} onChange={event => { retire(); setAliasCheck(event.target.checked); }} />Check operand aliasing</label></div>
      {!aliasCheck && <Status tone="warn">Aliasing check disabled. Deliberately broken mode: acceptance of the aliased operation is not quantum reversibility.</Status>}
      <div className="button-row"><button className="primary" onClick={() => { setResult(toyRoundTrip(aliased, aliasCheck)); setReversed(false); setRetired(false); }}><ArrowRight size={16} aria-hidden="true" />Apply CCX</button><button disabled={!result?.accepted || reversed} onClick={() => setReversed(true)}><ArrowRight size={16} aria-hidden="true" />Apply reverse</button></div>
      {retired && <Status testId="toy-retired">Result retired: operand or checker settings changed.</Status>}
      {result && !result.accepted && <Status tone="pass" verdict="rejected" testId="toy-verdict"><strong>{result.reason}</strong> The checked toy refuses this malformed operation.</Status>}
      {result?.accepted && <><div className="table-scroll" role="region" aria-label="Toy forward and reverse states" tabIndex={0}><table className="toy-table"><thead><tr><th scope="col">Input</th><th scope="col">After forward</th><th scope="col">After reverse</th></tr></thead><tbody>{result.rows.map(row => <tr key={row.state}><td><code>|{row.state.toString(2).padStart(result.width, '0')}&gt;</code></td><td><code>|{row.forward.toString(2).padStart(result.width, '0')}&gt;</code></td><td><code>{reversed ? `|${row.reverse.toString(2).padStart(result.width, '0')}>` : 'not applied'}</code></td></tr>)}</tbody></table></div>{reversed && <Status tone={result.reversible ? 'pass' : 'fail'} verdict={result.reversible ? 'reversible' : 'irreversible'} testId="toy-verdict"><strong>{result.reversible ? 'PASS: forward then reverse restores every input.' : 'FAILURE: forward then reverse cannot restore the lost input.'}</strong>{!result.reversible && ' Both |0> and |1> went to |0>. Accepted by the unchecked toy, but irreversible.'}</Status>}</>}
    </div>
    <div className="subsection"><h3>Disclosure without details still discloses something</h3><div className="reasons"><div><span>01</span><h4>Attention attracts effort</h4><p>Announcing a hidden result gives more people a reason to work on the same problem: Gidney's Streisand-effect argument.</p></div><div><span>02</span><h4>Existence is a useful hint</h4><p>Knowing a solution exists removes uncertainty about whether it is worth looking for one.</p></div><div><span>03</span><h4>The holder becomes identifiable</h4><p>A proof can identify who knows the secret, creating coercion risk even without revealing the secret itself.</p></div></div><Cite source="gidney" locator="The Problem with ZKPs; 1 Jun, edited 2 Jun" /><p className="caveat">Trail of Bits' broader lesson: ZK relocates trust to checker code, its compiler, and the proof system. It does not eliminate that trust.</p><Cite source="tob" locator="Postmortem conclusions" /></div>
    <div className="subsection"><h3>Primary-source timeline / 2026</h3><ol className="timeline" role="list">{timeline.map(([date, label, source]) => <li key={date + label} role="listitem"><time>{date}</time><strong>{label}</strong><Cite source={source} locator={date} /></li>)}</ol></div>
  </>;
}